name: Simple-Python-code-pipeline
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install pre-requisites
        run: pip install -r requirements.txt

      - name: run the test cases
        run: python3 test_hello.py

  Deploy:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: